TractorZoom/component-library

packages/number-field/src/number-field.js, packages/number-field/src/number-format-custom.js, stories/utilities/props/number-field.md
Removes auto focus as a default.
=> fix: removed autofocus, made variable to pass in

packages/basic-dialog/src/dialog.js
Removing withWidth higher order component and replacing with useMediaQuery hook to simplify testing.
=> fix: removing hoc for mediaquery hook

packages/basic-dialog/src/dialog.js
=> fix: removed width from dialog prop types

packages/number-field/src/number-field.js, stories/number-field/phone-number.stories.js
Changed number-field onChange to use onValueChange
=> feat: changed onChange to onValueChange

packages/side-panel/src/side-panel.js, packages/side-panel/src/styles.js, stories/utilities/props/side-panel.md, test/side-panel/src/__snapshots__/side-panel.spec.js.snap, test/side-panel/src/side-panel.spec.js
* updates the side panel to be a controlled component
* updates the header with close button to be sticky
=> feat: controlled side panel + sticky header

packages/select/src/listbox.js, packages/select/src/select.js
=> feat: add scroll to selected to select component

packages/basic-dialog/src/dialog.js, test/basic-dialog/src/dialog.spec.js
Adds data-tour to paper component in basic dialog
=> chore: add data-tour prop to dialog

packages/side-panel/src/side-panel.js, stories/side-panel/with-header-component.stories.js
=> feat: add dark blue background

packages/select/src/select.js, stories/select/add-new.stories.js, test/select/src/__snapshots__/select.spec.js.snap, test/select/src/select.spec.js
=> feat: add new option to select component

packages/select/src/select.js
=> fix: check that newValue exists before checking label property

packages/select/src/select.js
=> feat: only show add new option when no options exist

packages/places-select/src/places-select.js, test/places-select/src/__snapshots__/places-select.spec.js.snap
=> chore: spread props onto places autocomplete

packages/places-select/src/places-select.js, test/places-select/src/__snapshots__/places-select.spec.js.snap
=> chore: spread props places autocomplete

packages/places-select/src/index.js, packages/places-select/src/utilities.js
Add `getFullAddressString` utility to `places-select`
=> feat: add get full address string ulitity in places select

packages/select/src/select.js
=> fix: option to reverse sort order

packages/select/src/select.js
Reverts TractorZoom/component-library#143
=> revert: "fix: option to reverse sort order"

packages/places-select/src/places-select.js
=> fix: scope matching results to ones containing geolocaitons

packages/places-select/src/places-select.js
=> fix: undefined street number, add debug logging

packages/places-select/src/places-select.js
=> chore: debug statements not logging

packages/places-select/src/places-select.js
=> chore: log selected address

packages/places-select/src/places-select.js
=> feat: use place id instead of address on getGeocode

packages/places-select/src/places-select.js
=> feat: return empty string no streed number

packages/places-select/src/places-select.js
=> fix: set unfound address fields to  null

packages/places-select/src/places-select.js
=> fix: stop overwriting null address

packages/simple-select/.gitignore, packages/simple-select/.npmrc, packages/simple-select/README.md, packages/simple-select/babel.config.js, packages/simple-select/package-lock.json, packages/simple-select/package.json, packages/simple-select/src/hook.js, packages/simple-select/src/index.js, packages/simple-select/src/simple-select.js, packages/simple-select/src/styles.js, packages/text-field/src/hook.js, packages/text-field/src/styles.js, pages/index.js, pages/simple-select.js, test/text-field/src/__snapshots__/text-field.spec.js.snap
=> feat: add simple select component with updated styles

README.md, packages/basic-dialog/README.md, packages/button/README.md, packages/radio/.gitignore, packages/radio/.npmrc, packages/radio/README.md, packages/radio/babel.config.js, packages/radio/package-lock.json, packages/radio/package.json, packages/radio/src/hook.js, packages/radio/src/index.js, packages/radio/src/radio.js, packages/radio/src/styles.js, packages/simple-select/README.md, packages/text-field/README.md, packages/theme/README.md, pages/index.js, pages/radio.js
Add Radio component
Update example link for updated components
=> feat: add radio component

README.md, package.json, packages/places-select/package-lock.json, packages/places-select/package.json, packages/places-select/src/places-select.js, packages/places-select/src/styles.js, pages/_app.js, pages/index.js, pages/places-select.js, test/places-select/src/__snapshots__/places-select.spec.js.snap
=> feat: update places select styles

packages/places-select/src/index.js, packages/places-select/src/utilities.js
=> chore: export getLatLon func

packages/places-select/package.json, packages/places-select/src/index.js, packages/places-select/src/places-select.js, pages/places-select.js, test/places-select/src/places-select.spec.js
=> breaking: named export places select

packages/chip/.gitignore, packages/chip/.npmrc, packages/chip/README.md, packages/chip/babel.config.js, packages/chip/package-lock.json, packages/chip/package.json, packages/chip/src/chip.js, packages/chip/src/hook.js, packages/chip/src/index.js, packages/chip/src/styles.js, pages/chip.js, pages/index.js
Create chip wrapper and examples
Adds Feature or Fixes: # TZ-3189
See example preview link
=> feat: add custom chip component

packages/basic-dialog/src/styles.js
=> fix: update background color for dialog

packages/equipment-card/src/equipment-card.js, packages/equipment-card/src/styles.js
=> feat: move the click target to the circle only

packages/equipment-card/src/equipment-card.js, packages/equipment-card/src/styles.js
showing the card can still text wrap
showing the card will text break if message is too long
=> feat: break line at / if important feat line too long

packages/side-panel/src/side-panel.js
=> feat: remove themeProvider from side panel

packages/side-panel/src/styles.js
=> feat: sidepanel get background color from theme

packages/side-panel/src/side-panel.js, packages/side-panel/src/styles.js
=> feat: get background and text color for root from theme for sidePanel

packages/side-panel/src/side-panel.js, packages/side-panel/src/styles.js
=> Feat tz 3450 remove custom theme from side panel

packages/side-panel/src/side-panel.js
https://tractorzoom.github.io/component-library/?path=/story/side-panel--with-header-component
=> feat: readd themeProvider and update with new color theme

packages/theme/src/index.js, pages/theme.js
=> fix: adding logo to export
